---
- name: Converge
  hosts: all
  vars_files:
    - "../vars/install.yml"
    - "../vars/configure.yml"
  tasks:
    - name: "Import role"
      ansible.builtin.import_role:
        name: "plopoyop.warpgate"
