---
- name: Prepare
  hosts: all
  gather_facts: false
  vars_files:
    - "../vars/install.yml"
  tasks:
    - name: "Import role"
      ansible.builtin.import_role:
        name: "plopoyop.warpgate"
